'use client';

import { FormEvent, ReactNode } from 'react';
import { Download, LoaderCircle, RefreshCw } from 'lucide-react';

import type { Row } from '../types';
export const inputClass = 'mt-1.5 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-cyan-600';

export function Page({ title, intro, children, report }: { title: string; intro: string; children: ReactNode; report?: { summary: string; rows: Row[] } }) {
  return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-cyan-700">CiberGuate IA</p><h2 className="mt-2 text-3xl font-black">{title}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">{intro}</p></div>{report && <button onClick={() => void import('./reports').then(({ downloadDataReport }) => downloadDataReport(title, report.summary, report.rows))} className="flex items-center gap-2 rounded-xl border border-cyan-700 px-4 py-2 text-sm font-bold text-cyan-800"><Download size={17} />Exportar PDF</button>}</div>{children}</div>;
}
export function Panel({ title, children, action }: { title: string; children: ReactNode; action?: ReactNode }) { return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-5 flex items-center justify-between gap-4"><h3 className="text-lg font-black">{title}</h3>{action}</div>{children}</section>; }
export function Metric({ label, value, detail }: { label: string; value: ReactNode; detail: string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm font-semibold text-slate-500">{label}</p><p className="mt-2 text-3xl font-black">{value}</p><p className="mt-2 text-xs text-slate-500">{detail}</p></div>; }
export function FormCard({ onSubmit, submit, busy, children }: { onSubmit: (event: FormEvent<HTMLFormElement>) => void | Promise<void>; submit: string; busy?: boolean; children: ReactNode }) { return <form onSubmit={onSubmit} className="grid gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:grid-cols-2 xl:grid-cols-4">{children}<div className="flex items-end"><button disabled={busy} className="flex w-full items-center justify-center gap-2 rounded-xl bg-cyan-700 px-4 py-3 text-sm font-bold text-white disabled:opacity-60">{busy && <LoaderCircle size={16} className="animate-spin" />}{busy ? 'Procesando…' : submit}</button></div></form>; }
export function Field({ label, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string }) { return <label className="text-sm font-semibold">{label}<input required className={inputClass} {...props} /></label>; }
export function Select({ name, label, options, value, onChange }: { name: string; label: string; options: Array<readonly [string,string]>; value?: string; onChange?: React.ChangeEventHandler<HTMLSelectElement> }) { return <label className="text-sm font-semibold">{label}<select name={name} value={value} onChange={onChange} className={inputClass}>{options.map(([optionValue,text]) => <option key={optionValue} value={optionValue}>{text}</option>)}</select></label>; }
export function ErrorText({ text }: { text: string }) { return <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{text}</p>; }
export function SuccessText({ text }: { text: string }) { return <p className="rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">{text}</p>; }
export function LoadingBlock() { return <div className="flex items-center justify-center gap-3 rounded-2xl bg-white p-10 text-sm text-slate-500"><RefreshCw size={18} className="animate-spin" />Cargando información…</div>; }

export function DataTable({ rows, columns, labels, actions, onRow }: { rows: Row[]; columns: string[]; labels: string[]; actions?: (row: Row) => ReactNode; onRow?: (row: Row) => void }) {
  return <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{labels.map((label) => <th key={label} className="px-4 py-3">{label}</th>)}{actions && <th className="px-4 py-3">Acción</th>}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row) => <tr key={row.id} onClick={() => onRow?.(row)} className={onRow ? 'cursor-pointer hover:bg-cyan-50' : ''}>{columns.map((column) => <td key={column} className="max-w-xs px-4 py-3 text-slate-700">{formatValue(row[column])}</td>)}{actions && <td className="px-4 py-3" onClick={(event) => event.stopPropagation()}>{actions(row)}</td>}</tr>)}</tbody></table>{rows.length === 0 && <p className="p-10 text-center text-sm text-slate-500">Aún no hay registros.</p>}</div>;
}
export function formatValue(value: unknown): ReactNode { if (value === null || value === undefined || value === '') return '—'; if (typeof value === 'boolean') return value ? 'Sí' : 'No'; if (typeof value === 'object') return JSON.stringify(value); const text = String(value); return /^\d{4}-\d{2}-\d{2}T/.test(text) ? new Date(text).toLocaleString('es-GT') : text; }
export function mutationError(error: unknown) { const value = error as { data?: { detail?: string }; message?: string }; return value?.data?.detail ?? value?.message ?? 'No fue posible completar la operación'; }
