'use client';

import { Activity, AlertTriangle, BarChart3, Boxes, BrainCircuit, ChevronRight, ClipboardCheck, Download, LayoutDashboard, Menu, Plus, RefreshCw, Search, ShieldCheck, Sparkles, X } from 'lucide-react';
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';

type View = 'dashboard' | 'assets' | 'risks' | 'recommendations';
type Asset = { id: number; name: string; asset_type: string; owner: string; location: string; criticality: number; status: string };
type Risk = { id: number; title: string; threat: string; likelihood: number; impact: number; score: number; level: string; status: string; asset_id: number; asset_name?: string; nist_function: string };
type Recommendation = { id: string; title: string; detail: string; priority: string; framework: string };
type Dashboard = { total_assets: number; critical_assets: number; open_risks: number; critical_risks: number; average_risk_score: number; compliance_percentage: number; risks_by_level: Record<string, number> };

const API_BASE = process.env.NEXT_PUBLIC_API_BASE_URL ?? '/api/v1';
const demoAssets: Asset[] = [
  { id: 1, name: 'Portal de servicios ciudadanos', asset_type: 'Aplicación', owner: 'Tecnología', location: 'AWS Guatemala', criticality: 5, status: 'Activo' },
  { id: 2, name: 'Base de datos de contribuyentes', asset_type: 'Base de datos', owner: 'Finanzas', location: 'Centro de datos', criticality: 5, status: 'Activo' },
  { id: 3, name: 'Servidor de correo institucional', asset_type: 'Servidor', owner: 'Infraestructura', location: 'Nube privada', criticality: 4, status: 'Activo' },
  { id: 4, name: 'Red de sedes municipales', asset_type: 'Red', owner: 'Operaciones', location: 'Nacional', criticality: 3, status: 'En revisión' },
];
const demoRisks: Risk[] = [
  { id: 1, title: 'Acceso no autorizado a datos', threat: 'Credenciales comprometidas', likelihood: 5, impact: 5, score: 25, level: 'Crítico', status: 'Abierto', asset_id: 2, asset_name: demoAssets[1].name, nist_function: 'PROTECT' },
  { id: 2, title: 'Interrupción del portal público', threat: 'Ataque DDoS', likelihood: 4, impact: 4, score: 16, level: 'Alto', status: 'En tratamiento', asset_id: 1, asset_name: demoAssets[0].name, nist_function: 'RESPOND' },
  { id: 3, title: 'Propagación de ransomware', threat: 'Malware', likelihood: 3, impact: 5, score: 15, level: 'Alto', status: 'Abierto', asset_id: 3, asset_name: demoAssets[2].name, nist_function: 'RECOVER' },
  { id: 4, title: 'Configuración insegura de red', threat: 'Error de configuración', likelihood: 3, impact: 3, score: 9, level: 'Medio', status: 'Mitigado', asset_id: 4, asset_name: demoAssets[3].name, nist_function: 'IDENTIFY' },
];
const demoRecommendations: Recommendation[] = [
  { id: 'rec-1', title: 'Aplicar MFA a cuentas privilegiadas', detail: 'Exija un segundo factor resistente al phishing para reducir el riesgo de credenciales comprometidas.', priority: 'Crítica', framework: 'NIST PR.AA / CIS 6' },
  { id: 'rec-2', title: 'Definir protección contra DDoS', detail: 'Active límites de tráfico, WAF y un procedimiento probado de escalamiento con el proveedor.', priority: 'Alta', framework: 'NIST PR.IR / RS.MA' },
  { id: 'rec-3', title: 'Validar copias de seguridad aisladas', detail: 'Ejecute pruebas mensuales de restauración y mantenga una copia inmutable fuera del dominio.', priority: 'Alta', framework: 'NIST RC.RP / CIS 11' },
];
const demoDashboard: Dashboard = { total_assets: 24, critical_assets: 7, open_risks: 12, critical_risks: 3, average_risk_score: 13.8, compliance_percentage: 68, risks_by_level: { Crítico: 3, Alto: 5, Medio: 3, Bajo: 1 } };
const navItems = [
  { id: 'dashboard' as View, label: 'Resumen ejecutivo', icon: LayoutDashboard },
  { id: 'assets' as View, label: 'Inventario de activos', icon: Boxes },
  { id: 'risks' as View, label: 'Evaluación de riesgos', icon: ClipboardCheck },
  { id: 'recommendations' as View, label: 'Recomendaciones IA', icon: BrainCircuit },
];
const riskTone: Record<string, string> = { Crítico: 'bg-red-50 text-red-700 ring-red-200', Alto: 'bg-orange-50 text-orange-700 ring-orange-200', Medio: 'bg-amber-50 text-amber-700 ring-amber-200', Bajo: 'bg-emerald-50 text-emerald-700 ring-emerald-200' };

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`${API_BASE}${path}`, { ...init, headers: { 'Content-Type': 'application/json', ...init?.headers } });
  if (!response.ok) throw new Error(`API ${response.status}`);
  return response.json() as Promise<T>;
}

export default function Home() {
  const [view, setView] = useState<View>('dashboard');
  const [mobileMenu, setMobileMenu] = useState(false);
  const [assetModal, setAssetModal] = useState(false);
  const [riskModal, setRiskModal] = useState(false);
  const [assets, setAssets] = useState<Asset[]>(demoAssets);
  const [risks, setRisks] = useState<Risk[]>(demoRisks);
  const [recommendations, setRecommendations] = useState<Recommendation[]>(demoRecommendations);
  const [dashboard, setDashboard] = useState<Dashboard>(demoDashboard);
  const [demoMode, setDemoMode] = useState(true);
  const [loading, setLoading] = useState(false);
  const [search, setSearch] = useState('');

  const loadData = useCallback(async () => {
    setLoading(true);
    try {
      const [assetData, riskData, dashboardData, recommendationData] = await Promise.all([request<Asset[]>('/assets'), request<Risk[]>('/risks'), request<Dashboard>('/dashboard'), request<Recommendation[]>('/recommendations')]);
      setAssets(assetData); setRisks(riskData); setDashboard(dashboardData); setRecommendations(recommendationData); setDemoMode(false);
    } catch { setDemoMode(true); } finally { setLoading(false); }
  }, []);
  useEffect(() => {
    const timer = window.setTimeout(() => void loadData(), 0);
    return () => window.clearTimeout(timer);
  }, [loadData]);

  const filteredAssets = useMemo(() => assets.filter((a) => `${a.name} ${a.asset_type} ${a.owner}`.toLowerCase().includes(search.toLowerCase())), [assets, search]);
  const filteredRisks = useMemo(() => risks.filter((r) => `${r.title} ${r.threat} ${r.asset_name}`.toLowerCase().includes(search.toLowerCase())), [risks, search]);

  async function createAsset(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); const payload = { ...data, criticality: Number(data.criticality) };
    try { const created = await request<Asset>('/assets', { method: 'POST', body: JSON.stringify(payload) }); setAssets((c) => [created, ...c]); setDemoMode(false); }
    catch { setAssets((c) => [{ id: Date.now(), ...(payload as Omit<Asset, 'id'>) }, ...c]); }
    setAssetModal(false);
  }
  async function createRisk(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); const assetId = Number(data.asset_id); const payload = { ...data, asset_id: assetId, likelihood: Number(data.likelihood), impact: Number(data.impact) };
    try { await request<Risk>('/risks', { method: 'POST', body: JSON.stringify(payload) }); await loadData(); }
    catch { const score = Number(data.likelihood) * Number(data.impact); const level = score >= 20 ? 'Crítico' : score >= 12 ? 'Alto' : score >= 6 ? 'Medio' : 'Bajo'; setRisks((c) => [{ id: Date.now(), ...(payload as Omit<Risk, 'id' | 'score' | 'level' | 'asset_name'>), score, level, asset_name: assets.find((a) => a.id === assetId)?.name }, ...c]); }
    setRiskModal(false);
  }

  return <div className="min-h-screen bg-slate-50 text-slate-950">
    <aside className={`fixed inset-y-0 left-0 z-40 w-72 border-r border-slate-800 bg-[#071526] text-white transition-transform lg:translate-x-0 ${mobileMenu ? 'translate-x-0' : '-translate-x-full'}`}>
      <div className="flex h-20 items-center gap-3 border-b border-white/10 px-6"><span className="grid h-11 w-11 place-items-center rounded-xl bg-cyan-400 text-[#071526]"><ShieldCheck size={26} /></span><div><p className="text-lg font-bold">CiberGuate IA</p><p className="text-xs text-slate-400">Gestión preventiva</p></div><button className="ml-auto lg:hidden" onClick={() => setMobileMenu(false)} aria-label="Cerrar menú"><X /></button></div>
      <nav className="px-4 py-6" aria-label="Navegación principal"><p className="mb-3 px-3 text-[11px] font-semibold uppercase tracking-[0.18em] text-slate-500">Plataforma</p><div className="space-y-1.5">{navItems.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => { setView(id); setMobileMenu(false); setSearch(''); }} className={`flex w-full items-center gap-3 rounded-xl px-3.5 py-3 text-left text-sm font-medium ${view === id ? 'bg-cyan-400 text-[#071526]' : 'text-slate-300 hover:bg-white/7 hover:text-white'}`}><Icon size={19} />{label}{view === id && <ChevronRight className="ml-auto" size={17} />}</button>)}</div>
        <div className="mt-8 rounded-2xl border border-white/10 bg-white/5 p-4"><div className="mb-3 flex items-center gap-2 text-sm font-semibold"><Activity className="text-cyan-300" size={18} />Postura de seguridad</div><div className="mb-2 flex justify-between text-xs text-slate-300"><span>Cumplimiento</span><span>{dashboard.compliance_percentage}%</span></div><div className="h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-cyan-400" style={{ width: `${dashboard.compliance_percentage}%` }} /></div><p className="mt-3 text-xs leading-5 text-slate-400">Evaluación alineada con NIST CSF 2.0.</p></div>
      </nav><div className="absolute inset-x-0 bottom-0 border-t border-white/10 p-5"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-slate-700 text-sm font-bold">MG</span><div><p className="text-sm font-semibold">Municipalidad Central</p><p className="text-xs text-slate-400">Plan Profesional</p></div></div></div>
    </aside>
    <main className="min-h-screen lg:pl-72"><header className="sticky top-0 z-30 flex h-20 items-center border-b border-slate-200 bg-white/95 px-5 backdrop-blur md:px-8"><button onClick={() => setMobileMenu(true)} className="mr-3 rounded-lg p-2 hover:bg-slate-100 lg:hidden" aria-label="Abrir menú"><Menu /></button><div><p className="text-xs font-medium text-slate-500">Centro de control</p><h1 className="text-lg font-bold md:text-xl">{navItems.find((item) => item.id === view)?.label}</h1></div><div className="ml-auto flex items-center gap-2">{demoMode && <span className="hidden rounded-full bg-amber-50 px-3 py-1.5 text-xs font-semibold text-amber-700 ring-1 ring-amber-200 sm:inline-flex">Modo demostración</span>}<button onClick={() => void loadData()} disabled={loading} className="rounded-xl border border-slate-200 p-2.5" aria-label="Actualizar"><RefreshCw className={loading ? 'animate-spin' : ''} size={18} /></button><a href={`${API_BASE}/reports/executive.pdf`} className="hidden items-center gap-2 rounded-xl bg-[#071526] px-4 py-2.5 text-sm font-semibold text-white sm:flex"><Download size={17} />Informe PDF</a></div></header>
      <div className="mx-auto max-w-[1500px] p-5 md:p-8">{view === 'dashboard' && <DashboardView dashboard={dashboard} risks={risks} recommendations={recommendations} onNavigate={setView} />}{view === 'assets' && <AssetsView assets={filteredAssets} search={search} onSearch={setSearch} onAdd={() => setAssetModal(true)} />}{view === 'risks' && <RisksView risks={filteredRisks} search={search} onSearch={setSearch} onAdd={() => setRiskModal(true)} />}{view === 'recommendations' && <RecommendationsView recommendations={recommendations} />}</div>
    </main>{assetModal && <AssetModal onClose={() => setAssetModal(false)} onSubmit={createAsset} />}{riskModal && <RiskModal assets={assets} onClose={() => setRiskModal(false)} onSubmit={createRisk} />}
  </div>;
}

function DashboardView({ dashboard, risks, recommendations, onNavigate }: { dashboard: Dashboard; risks: Risk[]; recommendations: Recommendation[]; onNavigate: (view: View) => void }) {
  const max = Math.max(...Object.values(dashboard.risks_by_level), 1); const levels = ['Crítico', 'Alto', 'Medio', 'Bajo'];
  return <div className="space-y-7"><section className="overflow-hidden rounded-3xl bg-[#071526] p-6 text-white shadow-xl shadow-slate-200 md:p-8"><div className="flex flex-col gap-6 md:flex-row md:items-center md:justify-between"><div><div className="mb-3 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.18em] text-cyan-300"><Sparkles size={15} />Análisis inteligente</div><h2 className="max-w-2xl text-2xl font-bold leading-tight md:text-3xl">Su exposición actual requiere atención prioritaria.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">Hay {dashboard.critical_risks} riesgos críticos abiertos. Priorice identidad, continuidad y protección de datos.</p></div><button onClick={() => onNavigate('recommendations')} className="flex shrink-0 items-center justify-center gap-2 rounded-xl bg-cyan-400 px-5 py-3 text-sm font-bold text-[#071526]">Ver plan recomendado<ChevronRight size={18} /></button></div></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard title="Activos registrados" value={dashboard.total_assets} detail={`${dashboard.critical_assets} de alta criticidad`} icon={Boxes} tone="cyan" /><MetricCard title="Riesgos abiertos" value={dashboard.open_risks} detail={`${dashboard.critical_risks} requieren acción inmediata`} icon={AlertTriangle} tone="red" /><MetricCard title="Puntaje promedio" value={dashboard.average_risk_score.toFixed(1)} detail="Escala de riesgo 1 a 25" icon={BarChart3} tone="amber" /><MetricCard title="Cumplimiento NIST" value={`${dashboard.compliance_percentage}%`} detail="Meta recomendada: 85%" icon={ShieldCheck} tone="green" /></section>
    <section className="grid gap-6 xl:grid-cols-[1.35fr_1fr]"><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="font-bold">Riesgos por severidad</h3><p className="mt-1 text-sm text-slate-500">Distribución de riesgos activos</p><div className="mt-6 space-y-5">{levels.map((level) => { const count = dashboard.risks_by_level[level] ?? 0; return <div key={level}><div className="mb-2 flex justify-between text-sm"><span className="font-medium">{level}</span><span className="font-bold">{count}</span></div><div className="h-3 rounded-full bg-slate-100"><div className={`h-full rounded-full ${level === 'Crítico' ? 'bg-red-500' : level === 'Alto' ? 'bg-orange-500' : level === 'Medio' ? 'bg-amber-400' : 'bg-emerald-500'}`} style={{ width: `${count / max * 100}%` }} /></div></div>; })}</div></div>
      <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex justify-between"><div><h3 className="font-bold">Prioridades inteligentes</h3><p className="mt-1 text-sm text-slate-500">Acciones con mayor impacto</p></div><BrainCircuit className="text-cyan-600" /></div><div className="mt-5 space-y-3">{recommendations.slice(0, 3).map((item, i) => <div key={item.id} className="flex gap-3 rounded-xl bg-slate-50 p-3.5"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-lg bg-[#071526] text-xs font-bold text-white">{i + 1}</span><div><p className="text-sm font-semibold">{item.title}</p><p className="mt-1 text-xs text-slate-500">{item.framework}</p></div></div>)}</div></div></section>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 p-6"><div><h3 className="font-bold">Riesgos de mayor exposición</h3><p className="mt-1 text-sm text-slate-500">Ordenados por puntaje inherente</p></div><button onClick={() => onNavigate('risks')} className="text-sm font-semibold text-cyan-700">Ver todos</button></div><RiskTable risks={[...risks].sort((a, b) => b.score - a.score).slice(0, 5)} /></section></div>;
}
function MetricCard({ title, value, detail, icon: Icon, tone }: { title: string; value: string | number; detail: string; icon: typeof Boxes; tone: string }) { const colors: Record<string, string> = { cyan: 'bg-cyan-50 text-cyan-700', red: 'bg-red-50 text-red-600', amber: 'bg-amber-50 text-amber-700', green: 'bg-emerald-50 text-emerald-700' }; return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex justify-between"><div><p className="text-sm font-medium text-slate-500">{title}</p><p className="mt-2 text-3xl font-bold">{value}</p></div><span className={`grid h-11 w-11 place-items-center rounded-xl ${colors[tone]}`}><Icon size={21} /></span></div><p className="mt-4 text-xs text-slate-500">{detail}</p></div>; }
function SearchBar({ value, onChange, placeholder }: { value: string; onChange: (value: string) => void; placeholder: string }) { return <label className="relative block w-full md:max-w-sm"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={18} /><input value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} className="w-full rounded-xl border border-slate-200 bg-white py-2.5 pl-10 pr-4 text-sm outline-none focus:border-cyan-500 focus:ring-2 focus:ring-cyan-100" /></label>; }
function AssetsView({ assets, search, onSearch, onAdd }: { assets: Asset[]; search: string; onSearch: (value: string) => void; onAdd: () => void }) { return <div className="space-y-6"><PageIntro eyebrow="Superficie de ataque" title="Inventario de activos" description="Identifique y clasifique los recursos tecnológicos que sostienen la operación." /><div className="flex flex-col gap-3 sm:flex-row sm:justify-between"><SearchBar value={search} onChange={onSearch} placeholder="Buscar activo, tipo o responsable" /><PrimaryButton onClick={onAdd}><Plus size={18} />Registrar activo</PrimaryButton></div><div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-6 py-4">Activo</th><th className="px-5 py-4">Tipo</th><th className="px-5 py-4">Responsable</th><th className="px-5 py-4">Ubicación</th><th className="px-5 py-4">Criticidad</th><th className="px-5 py-4">Estado</th></tr></thead><tbody className="divide-y divide-slate-100">{assets.map((a) => <tr key={a.id}><td className="px-6 py-4 font-semibold">{a.name}</td><td className="px-5 py-4 text-slate-600">{a.asset_type}</td><td className="px-5 py-4 text-slate-600">{a.owner}</td><td className="px-5 py-4 text-slate-600">{a.location}</td><td className="px-5 py-4 font-bold">{a.criticality} <span className="font-normal text-slate-400">/ 5</span></td><td className="px-5 py-4"><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700 ring-1 ring-emerald-200">{a.status}</span></td></tr>)}</tbody></table></div></div>; }
function RisksView({ risks, search, onSearch, onAdd }: { risks: Risk[]; search: string; onSearch: (value: string) => void; onAdd: () => void }) { return <div className="space-y-6"><PageIntro eyebrow="NIST CSF 2.0" title="Evaluación de riesgos" description="Priorice amenazas mediante probabilidad, impacto y criticidad del activo." /><div className="flex flex-col gap-3 sm:flex-row sm:justify-between"><SearchBar value={search} onChange={onSearch} placeholder="Buscar riesgo, amenaza o activo" /><PrimaryButton onClick={onAdd}><Plus size={18} />Nueva evaluación</PrimaryButton></div><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><RiskTable risks={risks} /></div></div>; }
function RiskTable({ risks }: { risks: Risk[] }) { return <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-6 py-4">Riesgo / activo</th><th className="px-5 py-4">Amenaza</th><th className="px-5 py-4">Función NIST</th><th className="px-5 py-4">Puntaje</th><th className="px-5 py-4">Nivel</th><th className="px-5 py-4">Estado</th></tr></thead><tbody className="divide-y divide-slate-100">{risks.map((r) => <tr key={r.id}><td className="px-6 py-4"><p className="font-semibold">{r.title}</p><p className="mt-1 text-xs text-slate-500">{r.asset_name ?? `Activo #${r.asset_id}`}</p></td><td className="px-5 py-4 text-slate-600">{r.threat}</td><td className="px-5 py-4"><span className="rounded-md bg-slate-100 px-2 py-1 text-xs font-bold">{r.nist_function}</span></td><td className="px-5 py-4"><span className="text-lg font-bold">{r.score}</span><span className="text-slate-400"> / 25</span></td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ring-1 ${riskTone[r.level] ?? riskTone.Medio}`}>{r.level}</span></td><td className="px-5 py-4 text-slate-600">{r.status}</td></tr>)}</tbody></table>{risks.length === 0 && <p className="p-10 text-center text-sm text-slate-500">No se encontraron evaluaciones.</p>}</div>; }
function RecommendationsView({ recommendations }: { recommendations: Recommendation[] }) { return <div className="space-y-6"><PageIntro eyebrow="Motor de priorización" title="Recomendaciones inteligentes" description="Plan de acción generado a partir de sus riesgos, activos críticos y controles NIST." /><div className="grid gap-5 lg:grid-cols-2">{recommendations.map((item, i) => <article key={item.id} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#071526] font-bold text-cyan-300">{String(i + 1).padStart(2, '0')}</span><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold">{item.title}</h3><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ring-1 ${item.priority === 'Crítica' ? riskTone.Crítico : riskTone.Alto}`}>{item.priority}</span></div><p className="mt-3 text-sm leading-6 text-slate-600">{item.detail}</p><p className="mt-4 flex items-center gap-2 text-xs font-semibold text-cyan-700"><ShieldCheck size={15} />{item.framework}</p></div></div></article>)}</div><div className="rounded-2xl border border-cyan-200 bg-cyan-50 p-5 text-sm text-cyan-950"><div className="flex gap-3"><BrainCircuit className="shrink-0" size={21} /><p><strong>Cómo se prioriza:</strong> el motor combina severidad, criticidad del activo y función NIST afectada. Valide las recomendaciones antes de ejecutarlas.</p></div></div></div>; }
function PageIntro({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <div><p className="text-xs font-bold uppercase tracking-[0.16em] text-cyan-700">{eyebrow}</p><h2 className="mt-2 text-2xl font-bold md:text-3xl">{title}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">{description}</p></div>; }
function PrimaryButton({ onClick, children }: { onClick: () => void; children: React.ReactNode }) { return <button onClick={onClick} className="flex items-center justify-center gap-2 rounded-xl bg-cyan-500 px-4 py-2.5 text-sm font-bold text-[#071526]">{children}</button>; }
function ModalShell({ title, description, onClose, children }: { title: string; description: string; onClose: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/55 p-4 backdrop-blur-sm" onMouseDown={(e) => { if (e.target === e.currentTarget) onClose(); }}><div className="max-h-[92vh] w-full max-w-xl overflow-y-auto rounded-2xl bg-white shadow-2xl"><div className="flex justify-between border-b border-slate-100 p-6"><div><h2 className="text-xl font-bold">{title}</h2><p className="mt-1 text-sm text-slate-500">{description}</p></div><button onClick={onClose} aria-label="Cerrar"><X /></button></div>{children}</div></div>; }
const fieldClass = 'mt-1.5 w-full rounded-xl border border-slate-200 px-3.5 py-2.5 text-sm outline-none focus:border-cyan-500 focus:ring-2 focus:ring-cyan-100';
function FormActions({ onClose, label }: { onClose: () => void; label: string }) { return <div className="flex justify-end gap-3 border-t border-slate-100 pt-5"><button type="button" onClick={onClose} className="rounded-xl px-4 py-2.5 text-sm font-semibold text-slate-600">Cancelar</button><button type="submit" className="rounded-xl bg-[#071526] px-5 py-2.5 text-sm font-bold text-white">{label}</button></div>; }
function AssetModal({ onClose, onSubmit }: { onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <ModalShell title="Registrar activo" description="Agregue un recurso al inventario institucional." onClose={onClose}><form onSubmit={onSubmit} className="space-y-4 p-6"><label className="block text-sm font-semibold">Nombre<input required name="name" className={fieldClass} /></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Tipo<select name="asset_type" className={fieldClass}><option>Aplicación</option><option>Servidor</option><option>Base de datos</option><option>Red</option><option>Servicio en nube</option></select></label><label className="text-sm font-semibold">Criticidad<select name="criticality" className={fieldClass} defaultValue="3">{[1,2,3,4,5].map((n) => <option key={n}>{n}</option>)}</select></label></div><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Responsable<input required name="owner" className={fieldClass} /></label><label className="text-sm font-semibold">Ubicación<input required name="location" className={fieldClass} /></label></div><input type="hidden" name="status" value="Activo" /><FormActions onClose={onClose} label="Guardar activo" /></form></ModalShell>; }
function RiskModal({ assets, onClose, onSubmit }: { assets: Asset[]; onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <ModalShell title="Nueva evaluación" description="Califique probabilidad e impacto de 1 a 5." onClose={onClose}><form onSubmit={onSubmit} className="space-y-4 p-6"><label className="block text-sm font-semibold">Título<input required name="title" className={fieldClass} /></label><label className="block text-sm font-semibold">Activo<select required name="asset_id" className={fieldClass}>{assets.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label className="block text-sm font-semibold">Amenaza<input required name="threat" className={fieldClass} /></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Probabilidad<select name="likelihood" className={fieldClass} defaultValue="3">{[1,2,3,4,5].map((n) => <option key={n}>{n}</option>)}</select></label><label className="text-sm font-semibold">Impacto<select name="impact" className={fieldClass} defaultValue="3">{[1,2,3,4,5].map((n) => <option key={n}>{n}</option>)}</select></label></div><label className="block text-sm font-semibold">Función NIST<select name="nist_function" className={fieldClass}><option>GOVERN</option><option>IDENTIFY</option><option>PROTECT</option><option>DETECT</option><option>RESPOND</option><option>RECOVER</option></select></label><input type="hidden" name="status" value="Abierto" /><FormActions onClose={onClose} label="Evaluar riesgo" /></form></ModalShell>; }
