'use client';

import { FormEvent, useEffect, useState } from 'react';
import { LoaderCircle, ShieldCheck } from 'lucide-react';
import { useLocation, useNavigate } from 'react-router-dom';

import { setSession, useAppDispatch, useLoginMutation, useOauthCallbackMutation, useOauthConfigQuery, useVerifyMfaMutation } from '../store';
import type { Session } from '../types';
import { ErrorText, Field, mutationError } from '../components/ui';

export function LoginPage() {
  const navigate = useNavigate(); const dispatch = useAppDispatch(); const [error, setError] = useState(''); const [mfaToken, setMfaToken] = useState('');
  const [login, loginState] = useLoginMutation(); const [verify, verifyState] = useVerifyMfaMutation(); const oauth = useOauthConfigQuery(); const busy = loginState.isLoading || verifyState.isLoading;
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); const values = Object.fromEntries(new FormData(event.currentTarget)); try { const result = mfaToken ? await verify({ mfa_token: mfaToken, code: values.code }).unwrap() : await login({ email: values.email, password: values.password }).unwrap(); if ('mfa_required' in result) { setMfaToken(result.mfa_token); return; } dispatch(setSession(result as Session)); navigate('/dashboard'); } catch (cause) { setError(mutationError(cause)); } }
  return <main className="grid min-h-screen bg-[#061321] lg:grid-cols-[1.15fr_0.85fr]"><section className="hidden flex-col justify-between bg-[radial-gradient(circle_at_30%_20%,#0e7490_0%,#061321_55%)] p-16 text-white lg:flex"><div className="flex items-center gap-3 text-xl font-black"><ShieldCheck className="text-cyan-300" />CiberGuate IA</div><div><p className="mb-4 text-sm font-bold uppercase tracking-[.22em] text-cyan-300">Gestión preventiva de riesgos</p><h1 className="max-w-2xl text-5xl font-black leading-tight">Conozca en minutos su postura real de ciberseguridad.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-300">Diagnóstico, cumplimiento, monitoreo, SOC e inteligencia accionable en una sola plataforma.</p></div><p className="text-sm text-slate-400">MVP académico · NIST CSF 2.0 · ISO 27001 · CIS · OWASP · MITRE ATT&amp;CK</p></section><section className="flex items-center justify-center p-6"><form onSubmit={submit} className="w-full max-w-md rounded-3xl bg-white p-8 shadow-2xl"><h2 className="text-2xl font-black">{mfaToken ? 'Verificación MFA' : 'Acceso seguro'}</h2><p className="mb-7 mt-2 text-sm text-slate-500">{mfaToken ? 'Ingrese su código temporal de seis dígitos.' : 'Use sus credenciales institucionales.'}</p>{mfaToken ? <Field name="code" label="Código temporal" inputMode="numeric" /> : <div className="space-y-4"><Field name="email" label="Correo electrónico" type="email" /><Field name="password" label="Contraseña" type="password" /></div>}{error && <div className="mt-4"><ErrorText text={error} /></div>}<button disabled={busy} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-cyan-700 py-3 font-bold text-white disabled:opacity-60">{busy && <LoaderCircle size={17} className="animate-spin" />}Ingresar</button>{oauth.data?.enabled && <a href={oauth.data.authorization_url} className="mt-3 block rounded-xl border py-3 text-center text-sm font-bold">Ingresar con OAuth2 / OIDC</a>}</form></section></main>;
}

export function OauthCallbackPage() { const navigate = useNavigate(); const location = useLocation(); const dispatch = useAppDispatch(); const [callback] = useOauthCallbackMutation(); const [error, setError] = useState(''); useEffect(() => { const params = new URLSearchParams(location.search); void callback({ code: params.get('code'), state: params.get('state') }).unwrap().then((session) => { dispatch(setSession(session)); navigate('/dashboard', { replace: true }); }).catch((cause) => setError(mutationError(cause))); }, [callback, dispatch, location.search, navigate]); return <main className="flex min-h-screen items-center justify-center bg-[#071526] text-white"><div className="text-center"><LoaderCircle className="mx-auto animate-spin text-cyan-300" /><p className="mt-4">Validando identidad federada…</p>{error && <ErrorText text={error} />}</div></main>; }
