'use client';

import { FormEvent, useState } from 'react';
import { Download, Eye, ShieldAlert } from 'lucide-react';

import { DoughnutChart } from '../components/charts';
import { DataTable, ErrorText, Field, FormCard, LoadingBlock, Metric, Page, Panel, Select, SuccessText, mutationError } from '../components/ui';
import { notify, useAppDispatch, useAssetsQuery, useRunScanMutation, useScansQuery } from '../store';
import type { Finding, Scan } from '../types';

export function DiagnosticsPage() {
  const dispatch = useAppDispatch(); const scans = useScansQuery(); const assets = useAssetsQuery(); const [runScan, runState] = useRunScanMutation();
  const [selected, setSelected] = useState<Scan | null>(null); const [error, setError] = useState(''); const [success, setSuccess] = useState('');
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); setSuccess(''); const form = event.currentTarget; const values = Object.fromEntries(new FormData(form)); let target = String(values.target ?? '').trim(); if (!/^https?:\/\//i.test(target)) target = `https://${target}`; try { const result = await runScan({ ...values, target }).unwrap(); setSelected(result); setSuccess(`Diagnóstico completado: ${result.findings_count} hallazgos y riesgo ${result.risk_score}/100.`); dispatch(notify({ kind: 'success', message: 'Diagnóstico ejecutado y evidencia almacenada.' })); form.reset(); } catch (cause) { setError(mutationError(cause)); } }
  if (scans.isLoading) return <LoadingBlock />;
  const rows = scans.data ?? []; const active = selected ?? rows[0] ?? null; const findings = active?.findings ?? []; const severity = countSeverity(findings);
  return <Page title="Diagnóstico automático" intro="Ejecute comprobaciones no intrusivas y abra cada resultado para revisar evidencia, severidad y acciones correctivas." report={{ summary: 'Historial de diagnósticos ejecutados y almacenados.', rows }}><FormCard onSubmit={submit} submit="Ejecutar diagnóstico" busy={runState.isLoading}><Field name="target" label="URL autorizada" placeholder="https://servicio.gob.gt" /><Select name="asset_id" label="Activo relacionado" options={[['','Sin asociar'],...(assets.data ?? []).map((item) => [String(item.id),String(item.name)] as const)]} />{error && <ErrorText text={error} />}{success && <SuccessText text={success} />}</FormCard><section className="grid gap-4 sm:grid-cols-3"><Metric label="Diagnósticos ejecutados" value={rows.length} detail="Evidencia histórica" /><Metric label="Riesgo del seleccionado" value={`${active?.risk_score ?? 0}/100`} detail={active?.target ?? 'Seleccione un registro'} /><Metric label="Hallazgos encontrados" value={active?.findings_count ?? 0} detail="Abra el detalle inferior" /></section><DataTable rows={rows} columns={['target','status','risk_score','findings_count','summary','completed_at']} labels={['Objetivo','Estado','Riesgo / 100','Hallazgos','Resumen','Finalizado']} onRow={(row) => setSelected(row as Scan)} actions={(row) => <button className="flex items-center gap-1 font-bold text-cyan-700" onClick={() => setSelected(row as Scan)}><Eye size={15} />Ver hallazgos</button>} />{active && <section className="grid gap-6 xl:grid-cols-[.7fr_1.3fr]"><Panel title={`Severidad · ${active.target}`}><DoughnutChart title="Hallazgos" labels={Object.keys(severity)} values={Object.values(severity)} /><button onClick={() => void import('../components/reports').then(({ downloadDiagnosticReport }) => downloadDiagnosticReport(active))} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-cyan-700 px-4 py-3 font-bold text-white"><Download size={17} />Descargar informe PDF</button></Panel><Panel title={`Detalle de ${findings.length} hallazgos`}>{findings.length === 0 ? <SuccessText text="No se identificaron hallazgos en las comprobaciones ejecutadas." /> : <div className="space-y-3">{findings.map((finding, index) => <FindingCard key={`${finding.code}-${index}`} finding={finding} index={index} />)}</div>}</Panel></section>}</Page>;
}
function FindingCard({ finding, index }: { finding: Finding; index: number }) { const tone: Record<string,string> = { Crítica: 'border-red-300 bg-red-50', Alta: 'border-orange-300 bg-orange-50', Media: 'border-amber-300 bg-amber-50', Baja: 'border-blue-200 bg-blue-50' }; return <article className={`rounded-xl border p-4 ${tone[finding.severity] ?? 'border-slate-200'}`}><div className="flex flex-wrap items-center gap-2"><ShieldAlert size={18} /><span className="text-xs font-black uppercase">Hallazgo {index + 1} · {finding.severity}</span><code className="ml-auto text-xs">{finding.code}</code></div><h4 className="mt-2 font-black">{finding.title}</h4><p className="mt-2 text-sm"><strong>Evidencia:</strong> {finding.evidence}</p><p className="mt-1 text-sm"><strong>Recomendación:</strong> {finding.recommendation}</p></article>; }
function countSeverity(findings: Finding[]) { const result: Record<string,number> = { Crítica: 0, Alta: 0, Media: 0, Baja: 0 }; for (const finding of findings) result[finding.severity] = (result[finding.severity] ?? 0) + 1; return result; }
