'use client';

import { FormEvent } from 'react';
import { RefreshCw, Trash2 } from 'lucide-react';

import { BarChart, DoughnutChart } from '../components/charts';
import { DataTable, Field, FormCard, LoadingBlock, Page, Panel, Select, mutationError } from '../components/ui';
import { notify, useAlertsQuery, useAppDispatch, useAssetsQuery, useCheckMonitorMutation, useCreateAssetMutation, useCreateMonitorMutation, useCreateRiskMutation, useDeleteAssetMutation, useDeleteMonitorMutation, useDeleteRiskMutation, useMonitorsQuery, useRisksQuery, useUpdateAlertMutation } from '../store';

function values(event: FormEvent<HTMLFormElement>) { return Object.fromEntries(new FormData(event.currentTarget)); }
function useFeedback() { const dispatch = useAppDispatch(); return { ok: (message: string) => dispatch(notify({ kind: 'success', message })), fail: (error: unknown) => dispatch(notify({ kind: 'error', message: mutationError(error) })) }; }

export function AssetsPage() {
  const state = useAssetsQuery(); const [create, creating] = useCreateAssetMutation(); const [remove] = useDeleteAssetMutation(); const feedback = useFeedback(); const rows = state.data ?? [];
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form=event.currentTarget; const data=values(event); try { await create({ ...data, criticality: Number(data.criticality), status: 'Activo' }).unwrap(); form.reset(); feedback.ok('Activo registrado y reflejado en el inventario.'); } catch(error){ feedback.fail(error); } }
  if(state.isLoading) return <LoadingBlock/>; const criticalities=[1,2,3,4,5].map(level=>rows.filter(row=>Number(row.criticality)===level).length);
  return <Page title="Inventario de activos" intro="Registre, elimine y audite los recursos que sustentan la operación." report={{summary:'Inventario vigente de activos de información.',rows}}><FormCard onSubmit={submit} submit="Registrar activo" busy={creating.isLoading}><Field name="name" label="Nombre"/><Field name="asset_type" label="Tipo"/><Field name="owner" label="Responsable"/><Field name="location" label="Ubicación"/><Field name="criticality" label="Criticidad 1-5" type="number" min="1" max="5" defaultValue="3"/></FormCard><Panel title="Activos por criticidad"><BarChart title="Cantidad" labels={['1','2','3','4','5']} values={criticalities}/></Panel><DataTable rows={rows} columns={['name','asset_type','owner','location','criticality','status']} labels={['Activo','Tipo','Responsable','Ubicación','Criticidad','Estado']} actions={row=><button aria-label="Eliminar activo" className="text-red-600" onClick={async()=>{if(confirm('¿Eliminar este activo?')){try{await remove(row.id).unwrap();feedback.ok('Activo eliminado.');}catch(error){feedback.fail(error);}}}}><Trash2 size={17}/></button>}/></Page>;
}

export function RisksPage() {
  const risks=useRisksQuery(); const assets=useAssetsQuery(); const [create,creating]=useCreateRiskMutation(); const [remove]=useDeleteRiskMutation(); const feedback=useFeedback(); const rows=risks.data??[];
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=values(event);try{await create({...data,likelihood:Number(data.likelihood),impact:Number(data.impact),asset_id:Number(data.asset_id),status:'Abierto'}).unwrap();form.reset();feedback.ok('Riesgo calculado y priorizado.');}catch(error){feedback.fail(error);}}
  if(risks.isLoading)return <LoadingBlock/>; const distribution=Object.fromEntries(['Crítico','Alto','Medio','Bajo'].map(level=>[level,rows.filter(row=>row.level===level).length]));
  return <Page title="Evaluación de riesgos" intro="Calcule probabilidad × impacto, priorice y documente el tratamiento bajo NIST." report={{summary:'Matriz actual de riesgos de la organización.',rows}}><FormCard onSubmit={submit} submit="Evaluar riesgo" busy={creating.isLoading}><Field name="title" label="Título"/><Field name="threat" label="Amenaza"/><Field name="likelihood" label="Probabilidad 1-5" type="number" min="1" max="5"/><Field name="impact" label="Impacto 1-5" type="number" min="1" max="5"/><Select name="asset_id" label="Activo" options={(assets.data??[]).map(item=>[String(item.id),String(item.name)])}/><Select name="nist_function" label="Función NIST" options={['GOVERN','IDENTIFY','PROTECT','DETECT','RESPOND','RECOVER'].map(item=>[item,item])}/></FormCard><Panel title="Riesgos por nivel"><DoughnutChart title="Riesgos" labels={Object.keys(distribution)} values={Object.values(distribution)}/></Panel><DataTable rows={rows} columns={['title','asset_name','threat','nist_function','score','level','status']} labels={['Riesgo','Activo','Amenaza','NIST','Puntaje','Nivel','Estado']} actions={row=><button className="text-red-600" onClick={async()=>{if(confirm('¿Eliminar este riesgo?')){try{await remove(row.id).unwrap();feedback.ok('Riesgo eliminado.');}catch(error){feedback.fail(error);}}}}><Trash2 size={17}/></button>}/></Page>;
}

export function MonitoringPage() {
  const state=useMonitorsQuery();const [create,creating]=useCreateMonitorMutation();const [check,checking]=useCheckMonitorMutation();const [remove]=useDeleteMonitorMutation();const feedback=useFeedback();const rows=state.data??[];
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=values(event);let target=String(data.target??'').trim();if(!/^https?:\/\//i.test(target))target=`https://${target}`;try{await create({...data,target,interval_minutes:Number(data.interval_minutes)}).unwrap();form.reset();feedback.ok('Monitor creado y primera verificación ejecutada.');}catch(error){feedback.fail(error);}}
  if(state.isLoading)return <LoadingBlock/>;
  return <Page title="Evaluación continua" intro="Verifique disponibilidad, latencia y cumplimiento de los intervalos configurados." report={{summary:'Estado y métricas de los servicios monitoreados.',rows}}><FormCard onSubmit={submit} submit="Crear monitor" busy={creating.isLoading}><Field name="name" label="Nombre"/><Field name="target" label="URL" placeholder="https://servicio.gob.gt/health"/><Field name="interval_minutes" label="Intervalo (minutos)" type="number" min="1" max="1440" defaultValue="5"/></FormCard><Panel title="Disponibilidad por servicio"><BarChart title="Disponibilidad %" labels={rows.map(row=>String(row.name))} values={rows.map(row=>Number(row.availability_percentage))}/></Panel><DataTable rows={rows} columns={['name','target','status','availability_percentage','checks_successful','checks_total','latency_ms','last_checked_at']} labels={['Monitor','Objetivo','Estado','Disponibilidad %','Éxitos','Total','Latencia ms','Última revisión']} actions={row=><div className="flex gap-3"><button disabled={checking.isLoading} title="Verificar ahora" className="text-cyan-700" onClick={async()=>{try{await check(row.id).unwrap();feedback.ok('Verificación ejecutada y registrada.');}catch(error){feedback.fail(error);}}}><RefreshCw size={17}/></button><button title="Eliminar" className="text-red-600" onClick={async()=>{if(confirm('¿Eliminar este monitor?')){try{await remove(row.id).unwrap();feedback.ok('Monitor eliminado.');}catch(error){feedback.fail(error);}}}}><Trash2 size={17}/></button></div>}/></Page>;
}

export function AlertsPage(){const state=useAlertsQuery();const [update]=useUpdateAlertMutation();const feedback=useFeedback();const rows=state.data??[];if(state.isLoading)return <LoadingBlock/>;const grouped=Object.fromEntries(['Crítica','Alta','Media','Baja'].map(level=>[level,rows.filter(row=>row.severity===level).length]));return <Page title="Alertas inteligentes" intro="Revise la evidencia correlacionada y gestione el ciclo de atención." report={{summary:'Alertas generadas por diagnóstico, monitoreo y SIEM.',rows}}><Panel title="Alertas por severidad"><DoughnutChart title="Alertas" labels={Object.keys(grouped)} values={Object.values(grouped)}/></Panel><DataTable rows={rows} columns={['title','severity','source','status','detected_at','details']} labels={['Alerta','Severidad','Fuente','Estado','Detectada','Detalle']} actions={row=><select value={String(row.status)} onChange={async event=>{try{await update({id:row.id,status:event.target.value}).unwrap();feedback.ok('Estado de alerta actualizado.');}catch(error){feedback.fail(error);}}} className="rounded-lg border px-2 py-1 text-xs"><option>Nueva</option><option>Reconocida</option><option>Cerrada</option></select>}/></Page>}
